spring:
    profiles:
      active: local #environment
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
#      password: test
    h2:
      console:
        enabled: true
        path: /h2-console  # http://localhost:8080/h2-console
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    messages:
      basename: i18n/error
      encoding: UTF-8
      cache-duration: -1
      fallback-to-system-locale: false


server:
  port: 9000
  servlet:
    session:
      timeout: 50m

spring-doc:
  swagger-ui:
    tags-sorter: alpha # tag정렬
    operations-sorter : method
    doc-expansion : none #접기

jwt:
  secret: jwttestkey1234testjwttestjwttestjwttest
#  expire: 86400 # 1일
  expire: 31536000 # 1년 (365일)


szs:
  scrap-url: https://codetest.3o3.co.kr/v2/scrap